Try to fix JDK 1.6 gump instance failure by increasing the delay - testBlockedRemoveWithAddAll2 failed with the message "Both objects were removed expected:<0> but was:<1>"
see http://gump.zones.apache.org/gump/test/apache-commons/commons-collections/gump_work/build_apache-commons_commons-collections.html

git-svn-id: https://svn.apache.org/repos/asf/commons/proper/collections/trunk@645800 13f79535-47bb-0310-9956-ffa450edef68